# Add pinentry program preference
pinentry-program /usr/bin/pinentry-curses

# Cached passphrases expirations (currently 700 days)
max-cache-ttl 60480000
default-cache-ttl 60480000

# SSH agent configuration
enable-ssh-support
default-cache-ttl-ssh 60480000
max-cache-ttl-ssh 60480000
