[global/wm]
include-file = ~/.config/polybar/utils.ini
include-file = ~/.config/polybar/colors.ini

[bar/top]
override-redirect = false
width = 96%
height = 2.3%
offset-x = 2%
offset-y = 0.5%
border-size = 8pt
border-color = ${colors.nord}
background = ${colors.nord}
padding = 10pt
enable-ipc = true

#### Fonts

# Default
font-0 = JetBrainsMono Nerd Font:size=10:style=SemiBold;3

# Arch logo
font-1 = Symbols Nerd Font Mono:size=19;2

# Separators
font-2 = Symbols Nerd Font Mono:size=20;4

# Icons
font-3 = Font Awesome 6 Free Solid:size=10;3

# Nerd Font Icons (bspwm workspaces + VPN key)
font-4 = Symbols Nerd Font Mono:size=8;2

modules-center = left space-alt date space-alt right left space-alt hour space-alt right
modules-right = tray space left target right left space-alt vpn space-alt right left space-alt network space-alt right
bottom = false

[bar/bspwm]
inherit = bar/top
modules-left = arch space space dots space space left bspwm space-alt right left space-alt pulseaudio space-alt right left redshift right
wm-restack = bspwm

[bar/openbox]
inherit = bar/top
modules-left = arch space space dots space space left workspaces right left space-alt pulseaudio space-alt right left redshift right

#### Modules

[module/arch]
type = custom/text
format = <label>
label = %{F#0f94d2}%{T2}󰣇%{F-}%{T-}

click-left = rofi -show drun

[module/bspwm]
type = internal/bspwm

ws-icon-0 = I;%{F#FFCC80} 󰊠%{F-}
ws-icon-1 = II;%{F#EF9A9A} 󰊠%{F-}
ws-icon-2 = III;%{F#FFCC80} 󰊠%{F-}
ws-icon-3 = IV;%{F#CE93D8} 󰊠%{F-}
ws-icon-4 = V; 󰊠

label-focused = " 󰮯"
label-focused-font = 5
label-focused-foreground = #f7e900
label-focused-background = ${colors.nord1}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-font = 5
label-occupied-foreground = ${colors.nord6}
label-occupied-background = ${colors.nord1}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-font = 5
label-urgent-background = ${colors.nord1}
label-urgent-padding = 1

label-empty = " "
label-empty-font = 5
label-empty-foreground = ${colors.nord10}
label-empty-background = ${colors.nord1}
label-empty-padding = 1

[module/cpu]
type = internal/cpu
warn-percentage = 95

format = <label>
format-warn = <label-warn>
label = %{F#bf616a}%{T4} %{F-}%{T-} %percentage%%
label-warn = %{F#bf616a}%{T4}  %{T-}%percentage%%!%{F-}
label-background = ${colors.nord1}
label-warn-background = ${colors.nord1}

[module/date]
type = internal/date
interval = 5
label = %date%
date = %{F#d08770}%{T4} %{F-}%{T-} %Y-%m-%d
date-alt = %{F#d08770}%{T4} %{F-}%{T-} Today is %A
label-background = ${colors.nord1}
label-foreground = ${colors.nord6}

[module/hour]
type = internal/date
interval = 1
label = %date%
date = %{F#d08770}%{T4} %{F-}%{T-} %H:%M
label-background = ${colors.nord1}
label-foreground = ${colors.nord6}

[module/memory]
type = internal/memory
warn-percentage = 95

format = <label>
format-warn = <label-warn>
label = %{F#a3be8c}%{T4} %{F-}%{T-} %used%
label-warn = %{F#a3be8c}%{T4}  %used%!%{F-}%{T-}
label-background = ${colors.nord1}
label-warn-background = ${colors.nord1}

[module/network]
type = internal/network
interface = enp4s0

label-connected = %{T4} %{T-} %local_ip%
label-connected-foreground = ${colors.nord13}
label-connected-background = ${colors.nord1}

label-disconnected = %{T4} %{T-} Disconnected
label-disconnected-background = ${colors.nord1}
label-disconnected-foreground = ${colors.nord10}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = %{F#81a1c1}%{T4}  %{F-}%{T-}
format-volume = <label-volume>
format-volume-background = ${colors.nord1}
format-volume-foreground = ${colors.nord6}
format-muted-background = ${colors.nord1}
format-muted-foreground = ${colors.nord10}
label-volume = %percentage%%
label-muted = %{T4}  %{T-}Mute

click-middle = pavucontrol

[module/redshift]
type = custom/script
exec = redlight.sh check
tail = true

format = <label>
format-background = ${colors.nord1}
format-padding = 1

label = %output%

click-left = redlight.sh toggle

[module/target]
type = custom/script
exec = tg format polybar
tail = true

format = <label>
format-background = ${colors.nord1}
format-padding = 1

label = %output%

click-left = tg copy

[module/tray]
type = internal/tray
tray-spacing = 10px
tray-background = ${colors.nord}
tray-padding = 3px
tray-size = 70%

[module/vpn]
type=internal/network
interface = tun0

label-connected = %{T5}󰿂 %{T-} %local_ip%
label-connected-foreground = #7dcfff
label-connected-background = ${colors.nord1}

label-disconnected = %{T5}󰿂 %{T-} Disconnected
label-disconnected-background = ${colors.nord1}
label-disconnected-foreground = ${colors.nord10}

[module/workspaces]
type = internal/xworkspaces

icon-0 = I;%{F#FFCC80}󰊠 %{F-}
icon-1 = II;%{F#EF9A9A}󰊠 %{F-}
icon-2 = III;%{F#FFCC80}󰊠 %{F-}
icon-3 = IV;%{F#CE93D8}󰊠 %{F-}
icon-4 = V;󰊠 %{F-}

format = <label-state>

label-active = "󰮯 "
label-active-foreground = #f7e900
label-active-background = ${colors.nord1}
#label-active-underline = #fba922
label-active-padding = 1

label-occupied = %icon%
#label-occupied-underline = #555555
label-occupied-foreground = #ffffff
label-occupied-background = ${colors.nord1}
label-occupied-padding = 1

label-urgent = %{F#EF5350}󰊠 %{F-}
label-urgent-foreground = #000000
label-urgent-background = ${colors.nord1}
#label-urgent-underline = #9b0a20
label-urgent-padding = 1

label-empty = "󰧞 "
label-empty-foreground = ${colors.nord10}
label-empty-background = ${colors.nord1}
label-empty-padding = 1

[module/xkb]
type = internal/xkeyboard

format = <label-layout>
label-layout = %{T4} %{T-} %layout%
label-layout-foreground = #ce93d8
label-layout-background = ${colors.nord1}

[settings]
screenchange-reload = true
pseudo-transparency = false
