save-position-on-quit

vo=gpu-next
hwdec=yes

ao=pipewire

border=no
keepaspect-window=no

demuxer-max-back-bytes=300M

osc=yes
osd-bar=yes

screenshot-dir=$HOME/Sync/Pictures/Screenshots/mpv

ytdl-raw-options=yes-playlist=

cache=yes

[streamlink]
loop-playlist=inf
loop-file=inf
cache=no
