general {
        grace = 0
}

background {
        monitor =
        path = ~/Sync/Pictures/Wallpapers/ocarina.png
        blur_passes = 1
        blur_size = 6

}

label {
        monitor =

        text = $TIME
        color = rgba(255, 85, 102, 1)
        font_size = 100
        font_family = Road Rage
        rotate = 0

        valign = center
        halign = left
        position = 175, 100
}

input-field {
        monitor =

        size = 250, 50
        valign = center
        halign = left
        position = 250, -100

        dots_size = 0.2
        dots_spacing = 0.15
        dots_center = true
        dots_rounding = -1
        outline_thickness = 3

        inner_color = rgb(46,52,64)
        outer_color = rgb(46,52,64)
        font_color = rgb(d08770)
        # font_color = rgb(216,222,233)
        check_color = rgb(76,86,106)
        fail_color = rgb(255,85,102)

        capslock_color = -1
        numlock_color = -1
        bothlock_color = -1
        swap_font_color = false

        fade_on_empty = false
        fade_timeout = 4000
        placeholder_text = <b><i>Enter password...</i></b>
        hide_input = false
        rounding = 20 # -1 means complete rounding (circle/oval)
        fail_text = <i>$FAIL!</i>
        fail_transition = 300
        invert_numlock = false

}

label {
        monitor =

        text = $TIME
        color = rgba(255, 85, 102, 1)
        font_size = 100
        font_family = Road Rage
        rotate = 0

        valign = center
        halign = left
        position = 175, 100
}
