# ## Autostart applications
exec-once = wmname LG3D
exec = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"

exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset -i; echo '{"text": "<span face=\"JetBrainsMono NFM\"></span>  Off", "class": "off"}' > "$XDG_STATE_HOME"/waylight
exec-once = dunst > /tmp/dunst.log
exec-once = waybar > /tmp/waybar.log

exec-once = keepassxc
#exec-once = sleep 5 && localsend autostart
