# ## Window Rules config
# See https://wiki.hyprland.org/Configuring/Window-Rules

windowrule = suppressevent maximize, class:.*

windowrule = float, class:org.keepassxc.KeePassXC, title:Unlock Database - KeePassXC
windowrule = workspace 5 silent, class:org.keepassxc.KeePassXC, title:.* \[Locked\] - KeePassXC
windowrule = stayfocused, class:.*chatterino.*, title:.*'s Usercard.*
windowrule = move onscreen cursor -50% 0%, class:.*chatterino.*, title:.*'s Usercard.*
windowrule = float, class:pavucontrol
windowrule = float, class:org.kde.kdeconnect.daemon

#windowrule = idleinhibit focus, class:.*cemu.*
