# Font configuration
font_family      JetBrainsMono NFM Medium
bold_font        JetBrainsMono NFM Bold
italic_font      JetBrainsMono NFM Italic
bold_italic_font JetBrainsMono NFM Bold Italic
font_size 10

# General
enable_audio_bell no
background_opacity 0.70
window_padding_width 15
tab_bar_style powerline
enabled_layouts tall,fat,stack
paste_actions no-op

shell_integration no-cursor no-title
cursor_shape block

# Key mapping
 # New windows
map ctrl+shift+enter new_window_with_cwd
map alt+ctrl+shift+enter new_window

 # Jump between windows
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right

 # Move windows
map shift+up move_window up
map shift+down move_window down
map shift+right move_window right
map shift+left move_window left

 # Resize windows
map alt+ctrl+shift+l resize_window narrower
map alt+ctrl+shift+h resize_window wider
map alt+ctrl+shift+k resize_window taller
map alt+ctrl+shift+j resize_window shorter

 # Toggle layout
map ctrl+shift+z toggle_layout stack

 # Configure Kitty
map ctrl+shift+f2 edit_config_file
map ctrl+shift+f5 load_config_file

# BEGIN_KITTY_THEME
# Tokyo Night Storm
include current-theme.conf
# END_KITTY_THEME
